# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2317da77333437093b70a15f44c5cdf4f2c110a07ed2fd2d56ab72b197894bdb5beb580c2020d705df864accb94410eaf65623dbed47952c5a141b2019ad2f

test:
  secret_key_base: 1afc357bfa2a4d8591cc5fe6a69fcb372cd54f5bbc4887ca39b3c4c15e8b433ca99e1fc4a352e05744cf5f075e5b8fc2fed40808451720c4ea5bbc3d85fb6d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
